config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'
  resources :users
  resources :rooms
  resources :bookings
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ActiveRecord::Base
  has_many :bookings
  has_many :users, through: :bookings
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :bookings
  has_many :rooms, through: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all.order(:date)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/index.html.haml
%h1 Bookings#index
%p Find me in app/views/bookings/index.html.haml

app/views/dashboard/index.html.haml
%h1 This is the Dashboard 
%p this is the root route

app/views/layouts/_nav_bar.html.haml
%nav
  .nav-wrapper
    %a.brand-logo.center{href: '/'} BookIT
    %ul#nav-mobile.right.hide-on-med-and-down
      %li= link_to 'Rooms', rooms_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookItChurchAndState</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href='https://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script type="text/javascript" src="js/materialize.min.js"></script>
  <main>
    <%= render(partial: 'layouts/nav_bar') %>
    <%= yield %>
  </main>
</body>
</html>

app/views/rooms/index.html.haml
%h1.center Rooms and Spaces
.row.grey
  .col
    %h3.center Chapel
    %h5 This is our main area on the first floor. When you book it, the conference rooms will be unavailable for other users in order to avoid distractions.
.row
  .col
    %h3.center Basement
    %h5 Fully refurbished space, nest to our fully stocked kitchen.
.row.grey
  .col
    %h3.center Garage Conference Room
    %h5 Our biggest conference space. Unavailable when Chapel space is booked for an event.
.row
  .col
    %h3.center North Side Conference Room
    %h5 Equiped with white board and big flat-screen TV. Unavailable when Chapel space is booked for an event.
.row.grey
  .col
    %h3.center South Side Conference Room
    %h5 Equiped with white board and big flat-screen TV. Unavailable when Chapel space is booked for an event.

app/views/users/index.html.haml
%h1 Users#index
%p Find me in app/views/users/index.html.haml